#!/usr/bin/env bash
set -x

common=`pwd`

cmd="-s"
[ $1 = "--force" ] && cmd="-sf"

ln $cmd $common/.vim ~
ln $cmd $common/.vimrc ~
ln $cmd $common/.zshrc ~
ln $cmd $common/.bashrc ~
ln $cmd $common/.zsh_aliases ~
ln $cmd $common/.screenrc ~
ln $cmd $common/.gitconfig ~
ln $cmd $common/.gitignore ~
ln $cmd $common/.matplotlibrc ~
# ln $cmd $common/.00.py ~/.ipython/profile_default/startup/00.py
